CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "email" VARCHAR(100) UNIQUE NOT NULL,
  "password_hash" VARCHAR(255) NOT NULL,
  "role" ENUM(admin,student) NOT NULL
);

CREATE TABLE "students" (
  "student_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT UNIQUE NOT NULL,
  "hostel_name" VARCHAR(100) NOT NULL,
  "branch" VARCHAR(100) NOT NULL,
  "registration_status" ENUM(pending,approved) DEFAULT 'pending'
);

CREATE TABLE "admins" (
  "admin_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT UNIQUE NOT NULL
);

CREATE TABLE "fees_structure" (
  "fee_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "monthly_fee" DECIMAL(10,2) NOT NULL,
  "effective_from" DATE NOT NULL
);

CREATE TABLE "payments" (
  "payment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" INT NOT NULL,
  "fee_id" INT NOT NULL,
  "amount" DECIMAL(10,2) NOT NULL,
  "payment_status" ENUM(pending,paid) DEFAULT 'pending',
  "payment_date" DATE,
  "due_date" DATE NOT NULL,
  "month_year" VARCHAR(7) NOT NULL
);

CREATE TABLE "account_status" (
  "student_id" INT PRIMARY KEY,
  "is_blocked" BOOLEAN DEFAULT false,
  "blocked_reason" TEXT
);

COMMENT ON COLUMN "payments"."month_year" IS 'Format: YYYY-MM';

ALTER TABLE "students" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "admins" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "payments" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("student_id");

ALTER TABLE "payments" ADD FOREIGN KEY ("fee_id") REFERENCES "fees_structure" ("fee_id");

ALTER TABLE "account_status" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("student_id");
