CREATE TABLE "TodaysMenu" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "menu_date" date UNIQUE,
  "created_at" datetime
);

CREATE TABLE "BreakfastItems" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "description" text
);

CREATE TABLE "LunchItems" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "description" text
);

CREATE TABLE "DinnerItems" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "description" text
);

CREATE TABLE "TodaysBreakfast" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "todays_menu_id" int,
  "breakfast_item_id" int
);

CREATE TABLE "TodaysLunch" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "todays_menu_id" int,
  "lunch_item_id" int
);

CREATE TABLE "TodaysDinner" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "todays_menu_id" int,
  "dinner_item_id" int
);

COMMENT ON TABLE "TodaysBreakfast" IS 'Join table for TodaysMenu and BreakfastItems';

COMMENT ON TABLE "TodaysLunch" IS 'Join table for TodaysMenu and LunchItems';

COMMENT ON TABLE "TodaysDinner" IS 'Join table for TodaysMenu and DinnerItems';

ALTER TABLE "TodaysBreakfast" ADD FOREIGN KEY ("todays_menu_id") REFERENCES "TodaysMenu" ("id");

ALTER TABLE "TodaysBreakfast" ADD FOREIGN KEY ("breakfast_item_id") REFERENCES "BreakfastItems" ("id");

ALTER TABLE "TodaysLunch" ADD FOREIGN KEY ("todays_menu_id") REFERENCES "TodaysMenu" ("id");

ALTER TABLE "TodaysLunch" ADD FOREIGN KEY ("lunch_item_id") REFERENCES "LunchItems" ("id");

ALTER TABLE "TodaysDinner" ADD FOREIGN KEY ("todays_menu_id") REFERENCES "TodaysMenu" ("id");

ALTER TABLE "TodaysDinner" ADD FOREIGN KEY ("dinner_item_id") REFERENCES "DinnerItems" ("id");
